;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Notify.EnemyBrain.AdvanceSequence",DevComment="")
+GameplayTagList=(Tag="Notify.EnemyBrain.ClearFocus",DevComment="")
+GameplayTagList=(Tag="Notify.EnemyBrain.ClearStagger",DevComment="")
+GameplayTagList=(Tag="Notify.EnemyBrain.Dash",DevComment="")
+GameplayTagList=(Tag="Notify.EnemyBrain.SetFocus",DevComment="")
+GameplayTagList=(Tag="Notify.StateMachine.AirAttacking",DevComment="")
+GameplayTagList=(Tag="Notify.StateMachine.ClearActionState",DevComment="")
+GameplayTagList=(Tag="Notify.StateMachine.DeathFreeze",DevComment="")
+GameplayTagList=(Tag="Notify.StateMachine.Grounded",DevComment="")
+GameplayTagList=(Tag="Notify.StateMachine.Jump",DevComment="")
+GameplayTagList=(Tag="State.Action.Combat",DevComment="")
+GameplayTagList=(Tag="State.Action.Combat.Attack",DevComment="")
+GameplayTagList=(Tag="State.Action.Combat.Block",DevComment="")
+GameplayTagList=(Tag="State.Action.Combat.Dodge",DevComment="")
+GameplayTagList=(Tag="State.Action.Combat.Jump",DevComment="")
+GameplayTagList=(Tag="State.Action.Combat.Parry",DevComment="")
+GameplayTagList=(Tag="State.Action.Hit",DevComment="")
+GameplayTagList=(Tag="State.Action.Hit.Block",DevComment="")
+GameplayTagList=(Tag="State.Action.Hit.BlockBreak",DevComment="")
+GameplayTagList=(Tag="State.Action.Hit.Countered",DevComment="")
+GameplayTagList=(Tag="State.Action.Hit.Dead",DevComment="")
+GameplayTagList=(Tag="State.Action.Hit.Flinch",DevComment="")
+GameplayTagList=(Tag="State.Action.Hit.Knockback",DevComment="")
+GameplayTagList=(Tag="State.Action.Hit.Knockdown",DevComment="")
+GameplayTagList=(Tag="State.Action.Hit.Launch",DevComment="")
+GameplayTagList=(Tag="State.Action.Hit.Stagger",DevComment="")
+GameplayTagList=(Tag="State.Action.Hit.StaggerAir",DevComment="")
+GameplayTagList=(Tag="State.Action.None",DevComment="")
+GameplayTagList=(Tag="State.Movement.Airborne",DevComment="Airborne movement container state")
+GameplayTagList=(Tag="State.Movement.Airborne.Falling",DevComment="")
+GameplayTagList=(Tag="State.Movement.Airborne.Rising",DevComment="Airborne upward movement state")
+GameplayTagList=(Tag="State.Movement.Grounded",DevComment="Grounded movement container state")
+GameplayTagList=(Tag="State.Movement.Grounded.Locomotion",DevComment="Grounded movement state (idle/walk/jog)")

