;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="State.Movement.Grounded.Locomotion",NewTagName="State.Movement.Grounded.Walking")
+GameplayTagRedirects=(OldTagName="State.Action.Reaction.Hit.StaggerAir",NewTagName="State.Action.Reaction.Hit.Air")
+GameplayTagRedirects=(OldTagName="NotifyEvent.StateMachine.DeathFreeze",NewTagName="NotifyEvent.StateMachine.DeathFreeze?")
+GameplayTagList=(Tag="Attack.Motion.Dash",DevComment="")
+GameplayTagList=(Tag="Attack.Motion.Leap",DevComment="")
+GameplayTagList=(Tag="Attack.Motion.Stationary",DevComment="")
+GameplayTagList=(Tag="Attack.Motion.Teleport",DevComment="")
+GameplayTagList=(Tag="Attack.Type.AOE",DevComment="")
+GameplayTagList=(Tag="Attack.Type.Melee",DevComment="")
+GameplayTagList=(Tag="Attack.Type.Projectile",DevComment="")
+GameplayTagList=(Tag="Element.Air",DevComment="")
+GameplayTagList=(Tag="Element.Electric",DevComment="")
+GameplayTagList=(Tag="Element.Fire",DevComment="")
+GameplayTagList=(Tag="Element.Ice",DevComment="")
+GameplayTagList=(Tag="Element.Metal",DevComment="")
+GameplayTagList=(Tag="Element.None",DevComment="")
+GameplayTagList=(Tag="NotifyEvent.EnemyBrain.AdvanceSequence",DevComment="")
+GameplayTagList=(Tag="NotifyEvent.EnemyBrain.ClearFocus",DevComment="")
+GameplayTagList=(Tag="NotifyEvent.EnemyBrain.Dash",DevComment="")
+GameplayTagList=(Tag="NotifyEvent.EnemyBrain.Jump",DevComment="")
+GameplayTagList=(Tag="NotifyEvent.EnemyBrain.NotInterruptible",DevComment="")
+GameplayTagList=(Tag="NotifyEvent.EnemyBrain.RequestEvaluate",DevComment="")
+GameplayTagList=(Tag="NotifyEvent.EnemyBrain.SetFocus",DevComment="")
+GameplayTagList=(Tag="NotifyEvent.StateMachine.ClearActionState",DevComment="")
+GameplayTagList=(Tag="NotifyEvent.StateMachine.IfDead.PauseMontage",DevComment="")
+GameplayTagList=(Tag="NotifyEvent.StateMachine.Jump",DevComment="")
+GameplayTagList=(Tag="NotifyEvent.StateMachine.TryBounceGround",DevComment="")
+GameplayTagList=(Tag="NotifyEvent.StateMachine.TryLand",DevComment="")
+GameplayTagList=(Tag="NotifyEvent.StateMachine.TryWallSplat",DevComment="")
+GameplayTagList=(Tag="PlayerAction.Attack",DevComment="")
+GameplayTagList=(Tag="PlayerAction.Attack.Heavy.Hold",DevComment="")
+GameplayTagList=(Tag="PlayerAction.Attack.Heavy.Release",DevComment="")
+GameplayTagList=(Tag="PlayerAction.Attack.Heavy.Start",DevComment="")
+GameplayTagList=(Tag="PlayerAction.Attack.Light.Hold",DevComment="")
+GameplayTagList=(Tag="PlayerAction.Attack.Light.Release",DevComment="")
+GameplayTagList=(Tag="PlayerAction.Attack.Light.Start",DevComment="")
+GameplayTagList=(Tag="PlayerAction.Attack.Ninjutsu.Start",DevComment="")
+GameplayTagList=(Tag="PlayerAction.Block.Hold",DevComment="")
+GameplayTagList=(Tag="PlayerAction.Block.Release",DevComment="")
+GameplayTagList=(Tag="PlayerAction.Block.Start",DevComment="")
+GameplayTagList=(Tag="PlayerAction.Dodge",DevComment="")
+GameplayTagList=(Tag="PlayerAction.Jump.Release",DevComment="")
+GameplayTagList=(Tag="PlayerAction.Jump.Start",DevComment="")
+GameplayTagList=(Tag="PlayerAction.LockOnOff.Start",DevComment="")
+GameplayTagList=(Tag="PlayerAction.Look.Mouse",DevComment="")
+GameplayTagList=(Tag="PlayerAction.Look.Stick",DevComment="")
+GameplayTagList=(Tag="PlayerAction.Move",DevComment="")
+GameplayTagList=(Tag="PlayerAction.None",DevComment="")
+GameplayTagList=(Tag="State.Action.Combat",DevComment="")
+GameplayTagList=(Tag="State.Action.Combat.Attack",DevComment="")
+GameplayTagList=(Tag="State.Action.Combat.Block",DevComment="")
+GameplayTagList=(Tag="State.Action.Combat.Dodge",DevComment="")
+GameplayTagList=(Tag="State.Action.Combat.Jump",DevComment="")
+GameplayTagList=(Tag="State.Action.Combat.Parry",DevComment="")
+GameplayTagList=(Tag="State.Action.None",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Dead",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Hit",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Hit.Air",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Hit.Block",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Hit.BlockBreak",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Hit.BlockPerfect",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Hit.BounceGround",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Hit.BounceWall",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Hit.Countered",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Hit.Flinch",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Hit.Knockback",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Hit.Knockdown",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Hit.Launch",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Hit.Stagger",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Hit.WallSplat",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.None",DevComment="")
+GameplayTagList=(Tag="State.Movement.Airborne",DevComment="Airborne movement container state")
+GameplayTagList=(Tag="State.Movement.Airborne.Falling",DevComment="")
+GameplayTagList=(Tag="State.Movement.Airborne.Flying",DevComment="")
+GameplayTagList=(Tag="State.Movement.Grounded",DevComment="Grounded movement container state")
+GameplayTagList=(Tag="State.Movement.Grounded.Walking",DevComment="Grounded movement state (idle/walk/jog)")
+GameplayTagList=(Tag="Status.ActionBlocked.Attack",DevComment="")
+GameplayTagList=(Tag="Status.ActionBlocked.Block",DevComment="")
+GameplayTagList=(Tag="Status.ActionBlocked.Dodge",DevComment="")
+GameplayTagList=(Tag="Status.ActionBlocked.Jump",DevComment="")
+GameplayTagList=(Tag="Status.ActionBlocked.LockOnOff",DevComment="")
+GameplayTagList=(Tag="Status.ActionBlocked.Look",DevComment="")
+GameplayTagList=(Tag="Status.ActionBlocked.Move",DevComment="")
+GameplayTagList=(Tag="Status.ActionCancelableBy.Move",DevComment="")
+GameplayTagList=(Tag="Status.MovementLocked",DevComment="")
+GameplayTagList=(Tag="Status.MoveStatsOverride",DevComment="")

