;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="State.Action.Combat",DevComment="")
+GameplayTagList=(Tag="State.Action.None",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Block.Broken",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Block.Hit",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Death",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Flinch",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Knockback",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Knockdown",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Launch",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Parry",DevComment="")
+GameplayTagList=(Tag="State.Action.Reaction.Stagger",DevComment="")
+GameplayTagList=(Tag="State.Movement.Airborne",DevComment="Airborne movement container state")
+GameplayTagList=(Tag="State.Movement.Airborne.Falling",DevComment="")
+GameplayTagList=(Tag="State.Movement.Airborne.JumpStart",DevComment="")
+GameplayTagList=(Tag="State.Movement.Airborne.Rising",DevComment="Airborne upward movement state")
+GameplayTagList=(Tag="State.Movement.Grounded",DevComment="Grounded movement container state")
+GameplayTagList=(Tag="State.Movement.Grounded.JumpStart",DevComment="")
+GameplayTagList=(Tag="State.Movement.Grounded.Locomotion",DevComment="Grounded movement state (idle/walk/jog)")

